pub(crate) mod geolocation;
pub(crate) mod hardware;
pub(crate) mod identity;
pub(crate) mod locale;
pub(crate) mod media_features;
pub(crate) mod permissions;
pub(crate) mod screen;
pub(crate) mod timezone;
pub(crate) mod touch;
