FROM webscraper-eval/rust-stealth-oxided:latest

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libegl1-mesa \
        libgl1-mesa-dri \
        mesa-utils \
        xvfb \
    && rm -rf /var/lib/apt/lists/*
